FROM oznu/homebridge:latest
# RUN sudo apt-get update -y && sudo apt-get upgrade -y
# RUN sudo curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
# RUN sudo apt-get install -y nodejs git make g++ gcc
# # RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
# # RUN echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list<br>
# RUN sudo apt-get install yarn -y
# RUN sudo git clone https://github.com/Koenkk/zigbee2mqtt.git /opt/zigbee2mqtt
# RUN sudo chown -R pi:pi /opt/zigbee2mqtt
# EXPOSE 8080
